var inglesChino = [
['talk','shuo'],
['eat','chi'],
['want','yào'],
['teacher','shi'],
['yes','shì'],
['I/me','wô'],
['you','Nî'],
['good','hâo'],
['same/also','tóng'],
['study','xúe'],
['on/at/near','zài'],
['see','jìan'],
['name','míng zi'],
['thanks','xìe'],
['no/not','bù'],
['very','hên'],
['all/both','dou'],
['busy','máng'],
['cold','lêng'],
['wind','feng'],
['they/them','tamen'],
['old','lâo'],
['really','zhen'],
['dog','gôu'],
['cat','mao'],
['big','dà'],
['small','xiâo'],
['book','shu'],
['that','nà'],
['this','zhè'],
['tired','lèi(la)'],
['people','rén'],
['expensive','gùi'],
['call','jiào'],
['how','zên'],
['newspaper','bào'],
['women','nûrén'],
['scholar','xuézhe'],
['morning','zâoshàng'],
['evening','wânshàng'],
['clock','zhong'],
['teach','jiao'],
['short','âi'],
['think','xiâng'],
['like/enjoy','xîhuan'],
['more','gèng'],
['most','zùi'],
['some','yôu de'],
['tall','gao'],
['arrive','dao'],
['leg','tui'],
['men','nánrén'],
['understand','dông'],
['help','bang'],
['lead to','yînqî'],
['please','qîng'],
['close/shut','guan'],
['day','tian'],
['vehicle','che'],
['nose','bî zi'],
['song','ger'],
['pray','qí dâo'],
['remain','líu'],
['go(to place)','wâng'],
['correct','gâi'],
['please tell me','qîn wèn'],
['country','guójia'],
['new','xin'],
['battle','zhàn'],
['to enter','rù'],
['house','fáng zi']  
					];	//aáâà iíîì eéêè oóôò úûù 
