//version 2.16 - 24 feb 2009
var $o_sc = function () {
	var oVars={};oVars.funcName="$o_sc.fireCounter";oVars.actId="";oVars.sessionId="{{$creative.sessionId}}";oVars.counterUrl="";oVars.counterQS="";oVars.len=29;oVars.set=["optCounterSet","true"];oVars.evtForm="onsubmit";oVars.evtLink="onclick";oVars.oUsed={};oVars.imgArray=[];
	oVars.oAttribs={"a":["title", "alt", "innerHTML", "href", "id", "className"],"form":["name", "id", "action", "className"],"img":["alt", "title", "src", "id", "className"],"input":["alt", "title", "src", "id", "name", "value", "className"]};
	function getUsed(oUsed,attrib){if(oUsed && attrib && oUsed[attrib.toLowerCase()])return oUsed[attrib.toLowerCase()];else return null;};
	function addUsed(oUsed,attrib,el){if(!oUsed || !attrib || !el) return true;attrib = attrib.toLowerCase();if(oUsed[attrib] != null){var elUsed = oUsed[attrib];if(isArray(oUsed[attrib]))elUsed.push(el);else oUsed[attrib] = [elUsed];}else oUsed[attrib] = el;};function addUsed(oUsed, attrib, el){if(!oUsed || !attrib || !el) return true;attrib = attrib.toLowerCase();if(oUsed[attrib] != null){var elUsed = oUsed[attrib];if(isArray(oUsed[attrib]))elUsed.push(el);else {oUsed[attrib] = new Array(elUsed);oUsed[attrib].push(el);}}else oUsed[attrib] = el;};
	function isArray(obj){if(typeof(obj) == "object" && obj != null && typeof(obj.length) != "undefined" && !(obj.tagName && obj.tagName.toLowerCase() == "form"))return true;else return false;};
	function createImage(src){if(src){var c = oVars.imgArray.length;oVars.imgArray[c] = new Image();oVars.imgArray[c].src = src;}};
	return {
		setCounter:function(aElements,sAtrb,counter,qs){if(!aElements) return true;if(!isArray(aElements))aElements = new Array(aElements);counter = counter || oVars.counterUrl || "";qs = qs || oVars.counterQS || "";for(var i=0; i<aElements.length; i++){var el = aElements[i];var isNotSet = (el.getAttribute(oVars.set[0]) == oVars.set[1]) ? false : true;if(isNotSet){var sAttrib = sAtrb || "";var nAtrType = (!sAttrib) ? "none" : (sAttrib.lastIndexOf("_") + 1 == sAttrib.length) ? "append" : (sAttrib.lastIndexOf("_N") + 2 == sAttrib.length) ? "number" : "set";if(nAtrType != "set"){if(nAtrType == "number")sAttrib = sAttrib.replace(/_N+$/, "");else if(this.getElAttrib && this.getFormattedString) {sAttrib = this.getElAttrib(el, oVars.oAttribs);sAttrib = this.getFormattedString(sAttrib, sAtrb, oVars.len);}if(sAttrib != ""){var c=2;var tempAttrib = sAttrib;while(getUsed(oVars.oUsed, sAttrib.toLowerCase()) != null)sAttrib = tempAttrib + "_" + String(c++);}}if(sAttrib != ""){addUsed(oVars.oUsed, sAttrib, el);var sSrc = this.getSrc(counter, oVars.actId, oVars.sessionId, qs, sAttrib);this.setEvent(el, sSrc, oVars.funcName, oVars.evtLink, oVars.evtForm);el.setAttribute(oVars.set[0], oVars.set[1]);}}}},
		getElAttrib:function(el,oAttribs){if(!el || !oAttribs) return "";var tag = (el.tagName) ? el.tagName.toLowerCase() : "";var atrb = "";if(tag == "a" && el.getElementsByTagName("img")[0]){el = el.getElementsByTagName("img")[0];tag = "img";}else if(tag == "input" && (el.type && el.type.toLowerCase() != "image"))return "";if(oAttribs[tag] && isArray(oAttribs[tag])){var aAttribs = oAttribs[tag];for(var c=0; c<aAttribs.length; c++){var attrib = aAttribs[c];if(attrib == "innerHTML" && el.getElementsByTagName("*").length > 0 && el.hasChildNodes){for(var i=0; i<el.childNodes.length; i++){if(el.childNodes[i].nodeType == 3 && el.childNodes[i].nodeValue.match(/\w/g)){atrb += " " + el.childNodes[i].nodeValue;}}}atrb = atrb ||  el[attrib] || el.getAttribute(attrib) || "";if(atrb.match(/\w/))break;else atrb="";}}return atrb;},
		setEvent:function(el,src,fName,evtL,evtF){if(!el || !src || !fName)return true;evtL = evtL || "onclick";evtF = evtF || "onsubmit";var func = fName + "('" + src + "');";var evt = (el.tagName && el.tagName.toLowerCase() == "form") ? evtF : evtL;var tmpEvt = (el[evt]) ? el[evt].toString() : "";var tmpEvt=(tmpEvt != "") ? tmpEvt.substring(tmpEvt.indexOf("{") + 1, tmpEvt.lastIndexOf("}")) : "";func = func + tmpEvt;el[evt] = new Function(func);},
		setCounterVals:function(url,qs){if(url)oVars.counterUrl = url;if(qs)oVars.counterQS = qs;},
		setActivityId:function(actId,sessId){if(actId)oVars.actId = actId;if(sessId)oVars.sessionId = sessId;},
		getSrc:function(url,actId,sessId,qs,atrb){if(!url) return "";actId = actId || "";sessId = sessId || "";var sSrc = url + ((url.indexOf("?") == -1) ? "?" : "") + actId + "=" + sessId;if(qs && atrb)sSrc +="&" + qs + "=" + escape(atrb);return sSrc;},
		getUsed:function(){return oVars.oUsed;},
		addUsed:function(sAttrib,el,oUsed){oUsed = oUsed || oVars.oUsed;addUsed(oUsed, sAttrib, el)},
		getFormattedString:function(atrb,pre,len){if(!atrb) return "";len = len || 29;if(atrb.indexOf("//") > -1)atrb = atrb.substring(atrb.indexOf("//") + 2);if(atrb.lastIndexOf("/") > -1){if(atrb.lastIndexOf(".") > -1 && atrb.lastIndexOf(".") > atrb.lastIndexOf("/")  + 1){atrb = atrb.substring(atrb.lastIndexOf("/") +1, atrb.lastIndexOf("."));}}atrb = atrb.replace(/(&[a-z]+;)/g, "");atrb = atrb.replace(/^\s+|\s+$/, "");atrb = atrb.replace(/ in | for | the | of | at | on | to /ig, "_");atrb = atrb.replace(/\s|\.|\//g, "_");atrb = atrb.replace(/\W/g, "");if(pre)atrb = pre + atrb;atrb = (atrb.length > len) ? atrb.substring(0, len) : atrb;atrb = atrb.replace(/_+$/, "");return atrb;},
		fireCounter:function(src,srcDummy){if(!src)return true;srcDummy = srcDummy || "http://es.optimost.com/es/2/c/100/u/event.gif";for(var i=0; i<3; i++){if(i!=0) src = srcDummy;var rn=Math.floor(Math.random()*100000);src+= ((src.indexOf("?") == -1) ? "?" : "&") + "rn=" + rn;createImage(src);}return true;}
	};
}();
